[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
solc = "0.8.19"
src = "src"
test = "test"

[profile.ci]
fuzz_runs = 1_000
verbosity = 4

[rpc_endpoints]
anvil = "${ANVIL_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config